import time
from micropython import const
from sam2695_midi import Sam2695Midi
from sam2695_midi_chorus_reverberation import SAM2695_MIDI_REVERBERATION_ROOM_2
from sam2695_midi_note import (
    SAM2695_MIDI_NOTE_G_4,
    SAM2695_MIDI_NOTE_A_4,
    SAM2695_MIDI_NOTE_C_5,
    SAM2695_MIDI_NOTE_B_4,
    SAM2695_MIDI_NOTE_D_5,
    SAM2695_MIDI_NOTE_E_5,
    SAM2695_MIDI_NOTE_G_5,
    SAM2695_MIDI_NOTE_F_5,
)
from sam2695_midi_timbre import (
    SAM2695_MIDI_TIMBRE_BANK_0,
    SAM2695_MIDI_TIMBRE_BANK_0_ACOUSTIC_GUITAR_STEEL_STRING,
)

SAM2695_MIDI_PIN: int = const(17)

CHANNEL: int = const(0)
CHANNEL_VOLUME: int = const(110)

REVERBERATION_VOLUME: int = const(80)
REVERBERATION_DELAY_FEEDBACK: int = const(0)

QUARTER_NOTE_DURATION: int = const(300)
EIGHTH_NOTE_DURATION: int = 150
DOTTED_QUARTER_NOTE_DURATION: int = const(450)

sam2695_midi = Sam2695Midi(tx_pin=SAM2695_MIDI_PIN)


def play_note(midi_note: int, duration: int, note_velocity: int = 90):
    sam2695_midi.note_on(CHANNEL, midi_note, note_velocity)
    time.sleep_ms(duration)
    sam2695_midi.note_off(CHANNEL, midi_note)
    time.sleep_ms(30)


sam2695_midi.set_channel_timbre(
    CHANNEL,
    SAM2695_MIDI_TIMBRE_BANK_0,
    SAM2695_MIDI_TIMBRE_BANK_0_ACOUSTIC_GUITAR_STEEL_STRING,
)
sam2695_midi.set_channel_volume(CHANNEL, CHANNEL_VOLUME)
sam2695_midi.set_reverberation(
    CHANNEL,
    SAM2695_MIDI_REVERBERATION_ROOM_2,
    REVERBERATION_VOLUME,
    REVERBERATION_DELAY_FEEDBACK,
)

while True:
    play_note(SAM2695_MIDI_NOTE_G_4, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_G_4, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_A_4, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_G_4, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_C_5, DOTTED_QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_B_4, DOTTED_QUARTER_NOTE_DURATION)
    time.sleep_ms(QUARTER_NOTE_DURATION)

    play_note(SAM2695_MIDI_NOTE_G_4, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_G_4, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_A_4, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_G_4, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_D_5, DOTTED_QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_C_5, DOTTED_QUARTER_NOTE_DURATION)
    time.sleep_ms(QUARTER_NOTE_DURATION)

    play_note(SAM2695_MIDI_NOTE_G_4, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_G_4, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_G_5, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_E_5, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_C_5, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_B_4, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_A_4, DOTTED_QUARTER_NOTE_DURATION)
    time.sleep_ms(QUARTER_NOTE_DURATION)

    play_note(SAM2695_MIDI_NOTE_F_5, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_F_5, EIGHTH_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_E_5, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_C_5, QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_D_5, DOTTED_QUARTER_NOTE_DURATION)
    play_note(SAM2695_MIDI_NOTE_C_5, DOTTED_QUARTER_NOTE_DURATION)

    time.sleep_ms(5000)
